#!/usr/bin/env python3
"""
Convert a TTF into the ThingPulse OLEDDisplay bitmap font format, so a custom
typeface can be used by the ST7789 (and any OLEDDisplay-based) text path with no
driver changes -- drawString() and getStringWidth() keep working unchanged.

Format (see src/helpers/ui/OLEDDisplay.{h,cpp}):
  byte[0]            width      (max glyph width; informational, unused by renderer)
  byte[1] HEIGHT_POS  height     (text cell height in pixels = ascent + descent)
  byte[2] FIRST_CHAR_POS firstChar (ASCII, typically 32)
  byte[3] CHAR_NUM_POS  numChars
  then numChars * 4-byte jump table entries: [offsetHi, offsetLo, byteSize, advanceWidth]
    offset 0xFFFF => non-drawable sentinel (advance only, e.g. space)
  then glyph bitmap data, column-major, 1 byte = 8 vertical pixels (LSB = top,
        matching OLEDDisplay::setPixel which uses bit (y&7)),
        rasterHeight = ceil(height/8) bytes per column, byteSize = width*rasterHeight.

Usage:
    pip install pillow
    python3 tools/oled_font.py <input.ttf> <size> <output.h> <symbol> [firstChar] [numChars]
"""
import sys

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:
    sys.exit("Pillow is required: pip install pillow")


def build(ttf_path, size, out_path, symbol, first_char=32, num_chars=224):
    font = ImageFont.truetype(ttf_path, size)
    ascent, descent = font.getmetrics()
    text_height = ascent + descent
    raster_height = (text_height + 7) // 8  # == 1 + ((height-1) >> 3)

    jump = []
    glyph_data = bytearray()
    cur_offset = 0
    max_w = 0
    drawn = 0

    for code in range(first_char, first_char + num_chars):
        ch = chr(code)
        try:
            advance = int(round(font.getlength(ch)))
        except Exception:
            advance = 0
        if advance < 0:
            advance = 0
        if advance > max_w:
            max_w = advance

        if advance == 0:
            jump.append((0xFF, 0xFF, 0x00, 0))  # no advance -> skip
            continue

        # Render glyph into an advance-wide cell, baseline at `ascent` (anchor 'la'
        # = left/ascender, so the ascender line sits at y=0).
        img = Image.new("L", (advance, text_height), 0)
        ImageDraw.Draw(img).text((0, 0), ch, font=font, fill=255, anchor="la")
        px = img.load()

        has_ink = any(px[x, y] for x in range(advance) for y in range(text_height))
        if not has_ink:
            jump.append((0xFF, 0xFF, 0x00, advance))  # space-like / undefined
            continue

        glyph_bytes = bytearray(advance * raster_height)
        for x in range(advance):
            for r in range(raster_height):
                b = 0
                for bit in range(8):
                    py = r * 8 + bit
                    if py < text_height and px[x, py]:
                        b |= 1 << bit     # LSB = top (matches OLEDDisplay: setPixel uses bit (y&7))
                glyph_bytes[x * raster_height + r] = b

        jump.append(((cur_offset >> 8) & 0xFF, cur_offset & 0xFF,
                     advance * raster_height, advance))
        glyph_data.extend(glyph_bytes)
        cur_offset += advance * raster_height
        drawn += 1

    out = bytearray([max_w & 0xFF, text_height & 0xFF, first_char & 0xFF, num_chars & 0xFF])
    for msb, lsb, sz, w in jump:
        out += bytes((msb, lsb, sz, w))
    out += glyph_data

    with open(out_path, "w") as f:
        f.write("// Auto-generated by tools/oled_font.py -- do not edit by hand.\n")
        f.write(f"// TTF: {ttf_path}  pixel size: {size}  cell height: {text_height}"
                f"  chars: {first_char}-{first_char + num_chars - 1}\n")
        f.write("#pragma once\n")
        f.write("#include <Arduino.h>\n")
        f.write(f"const uint8_t {symbol}[] PROGMEM = {{\n")
        for i in range(0, len(out), 16):
            f.write("  " + "".join("0x{:02X}, ".format(b) for b in out[i:i + 16]) + "\n")
        f.write("};\n")

    print(f"{symbol}: cell_height={text_height} raster={raster_height} "
          f"advance_max={max_w} drawn={drawn}/{num_chars} bytes={len(out)}")


def main():
    if len(sys.argv) < 5:
        sys.exit("usage: oled_font.py <input.ttf> <size> <output.h> <symbol> [firstChar] [numChars]")
    ttf = sys.argv[1]
    size = int(sys.argv[2])
    out = sys.argv[3]
    sym = sys.argv[4]
    fc = int(sys.argv[5]) if len(sys.argv) > 5 else 32
    nc = int(sys.argv[6]) if len(sys.argv) > 6 else 224
    build(ttf, size, out, sym, fc, nc)


if __name__ == "__main__":
    main()
