#!/usr/bin/env python3
"""
Convert a PNG into an RGB565 C array for the ST7789 RGB boot logo.

Usage:
    pip install pillow
    python3 tools/rgb565_logo.py <input.png> <output.h> <symbol> [WxH]

The emitted array is STANDARD RGB565 ( ((r&0xF8)<<8)|((g&0xFC)<<3)|(b>>3) ),
placed in flash via PROGMEM. The ST7789 driver byte-swaps each pixel on the fly
while blitting (see ST7789Spi::drawRGBBitmap), so this asset stays portable.

If WxH is given (e.g. 200x100) the image is resized to exactly those dimensions
with no separate cropping step. RGBA inputs are supported; the alpha channel is
ignored (pixels are expected to be opaque, composited onto the desired
background in the source image).
"""
import sys
import struct

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow is required: pip install pillow")


def pack_rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def main():
    if len(sys.argv) < 4:
        sys.exit("usage: rgb565_logo.py <input.png> <output.h> <symbol> [WxH]")
    in_path = sys.argv[1]
    out_path = sys.argv[2]
    symbol = sys.argv[3]
    target = None
    if len(sys.argv) >= 5:
        w, h = sys.argv[4].lower().split("x")
        target = (int(w), int(h))

    im = Image.open(in_path).convert("RGBA")
    if target is not None:
        if im.size != target:
            im = im.resize(target, Image.LANCZOS)
            print(f"resized to {im.size[0]}x{im.size[1]}")
        else:
            print(f"source already {im.size[0]}x{im.size[1]} (no resize)")
    w, h = im.size
    px = im.load()

    vals = []
    for y in range(h):
        for x in range(w):
            r, g, b, _a = px[x, y]
            vals.append(pack_rgb565(r, g, b))

    with open(out_path, "w") as f:
        f.write("// Auto-generated by tools/rgb565_logo.py -- do not edit by hand.\n")
        f.write(f"// Source: {in_path}  Size: {w}x{h}  Format: RGB565 (standard)\n")
        f.write("#pragma once\n")
        f.write("#include <Arduino.h>\n")
        f.write(f"#define MESHCORE_LOGO_RGB_W {w}\n")
        f.write(f"#define MESHCORE_LOGO_RGB_H {h}\n")
        f.write(f"static const uint16_t {symbol}[{w * h}] PROGMEM = {{\n")
        for row in range(h):
            chunk = vals[row * w:(row + 1) * w]
            f.write("  " + "".join("0x{:04X}, ".format(v) for v in chunk) + "\n")
        f.write("};\n")

    print(f"wrote {out_path}: {w}x{h} = {w * h} pixels ({w * h * 2} bytes)")


if __name__ == "__main__":
    main()
